/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iT0bgVtk64g
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import Link from "next/link"
import { DialogFormProfile } from "@/components/component/dialog-form-profile"

export function Profile() {
  return (
    <div className="w-full max-w-3xl mx-auto">
      <div className="bg-muted rounded-lg overflow-hidden">
        <div className="bg-[#888888] h-32 relative">
          <div className="absolute -bottom-12 left-6">
            <Avatar className="w-24 h-24 border-4 border-background">
              <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </div>
        </div>
        <div className="pt-16 px-6 pb-6 grid gap-4">
          <div className="flex items-center justify-between">
            <div className="grid gap-1">
              <h2 className="text-2xl font-bold">John Doe</h2>
            </div>
            <DialogFormProfile />
          </div>

          {/* <div className="grid grid-cols-3 gap-4 text-center">
            <div className="space-y-1">
              <p className="text-2xl font-bold">100</p>
              <p className="text-muted-foreground">Configuration</p>
            </div>
            <div className="space-y-1">
              <p className="text-2xl font-bold">1.2K</p>
              <p className="text-muted-foreground">Followers</p>
            </div>
            <div className="space-y-1">
              <p className="text-2xl font-bold">500</p>
              <p className="text-muted-foreground">Following</p>
            </div>
          </div> */}
        </div>
      </div>
      <div className="mt-6 grid gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Mes dernières configurations</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  width={100}
                  height={100}
                  alt="Post thumbnail"
                  className="rounded-lg"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <div className="grid gap-2">
                  <h3 className="text-lg font-semibold">Mon PC gaming</h3>
                  <p className="text-muted-foreground">
                    Prix minimum de la configuration : 1900€
                  </p>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <CalendarDaysIcon className="h-4 w-4" />
                    <span>Aug 21, 2023</span>
                  </div>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  width={100}
                  height={100}
                  alt="Post thumbnail"
                  className="rounded-lg"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <div className="grid gap-2">
                  <h3 className="text-lg font-semibold">Pc pour michel en 3D design</h3>
                  <p className="text-muted-foreground">
                    Prix minimum de la configuration : 1500€
                  </p>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <CalendarDaysIcon className="h-4 w-4" />
                    <span>Aug 15, 2023</span>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
          <CardFooter>
            <Link href="/configuration" className="text-primary" prefetch={false}>
              Voir toutes mes configurations
            </Link>
            <button className="transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none ...">
              Hover me
            </button>
          </CardFooter>
        </Card>
      </div>
    </div >
  )
}

function CalendarDaysIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}
