import Image from "next/image";
import { Home } from "@/components/component/home";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <div>
      <Home />
    </div>

  );
}
