/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/c3oqP9RTPRY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { TextHoverEffect } from "@/components/ui/text-hover-effect";
import { TimelineHome } from "@/components/component/timeline/TimeLineHome";
import { FlipWordsHome } from "@/components/component/flipWordHome/FlipWordHome";

export function Home() {
  return (
    <div className="flex flex-col">
      <main className="">
        <div className="h-screen flex items-center justify-center">
          <TextHoverEffect text="Reactomatic" />
        </div>
        <TimelineHome />
        <FlipWordsHome />

      </main>
    </div>
  )
}

